### ISSUE TITLE
How to install multiple quill on the same page?

### ISSUE THREAD

**Issue by nobutsta** [Weavy/bootstrap-quill#2]
I have 3 input-textareas on the same page. And want to install quill on all. I changed from ID into ClassName hoping it will activate all the inputs - but unlucky. How to do so?

**Comment by klasjersevi** [comment]
You will need one Quill instance for each place you want quill, as the quill constructor only uses the first matched element in a selector. So you can use querySeletorAll or jQuery, then loop over the collection of elements to create instances for each container.

Read more at https://quilljs.com/docs/configuration/

```js
var options = { /* editor options */ };

document.querySelectorAll('.editor').forEach(function(container) {
    new Quill(container, options);
});
```
