### ISSUE TITLE
Layout looks broken

### ISSUE THREAD

**Issue by davidnash** [Weavy/bootstrap-quill#3]
Hello, I'm using regular Quill in a bootstrap project, and I came across this, and would prefer to use it instead.

I did `npm uninstall quill` and `npm install bootstrap-quill --save`, and then in my SCSS have this:
```
// @import '~quill/dist/quill.snow.css';
@import '~bootstrap-quill/scss/quill.snow';
```

and in my js I did this:
```
var Quill = require('bootstrap-quill');
// var Quill = require('quill');
```

then I did `npm run dev`, and it looks like this:

![bootstrap-quill](https://user-images.githubusercontent.com/274968/82004940-6ebff480-96a7-11ea-82a0-b5d14d7a2b6b.gif)

whereas quill "classic" looks like this:

![quill](https://user-images.githubusercontent.com/274968/82004955-78495c80-96a7-11ea-815d-7fae48f88d96.gif)

The only other code that's changed is adding a white background to the quill editor div.

Thanks for your help!

cheers,
David

**Comment by klasjersevi** [comment]
I think you don't have the css configured correctly. You will need both the quill.scss and also any of or both of quill.snow.scss and quill.bubble.scss.

Note that you may also need to include the svg sprite file somewhere. See the dist folder for assets needed. See package.json for details on what needs to be built if you want to include it in your build.

See the demo/index.html for a running example.

**Comment by davidnash** [comment]
Thanks for your quick response, Klas.

I now have:
```
@import '~bootstrap-quill/scss/quill';
@import '~bootstrap-quill/scss/quill.snow';
```
And it doesn't look broken any more, but the icons aren't displaying.

The demo is working fine. 

In Chrome web dev inspector, in the demo I see this:

![demo](https://user-images.githubusercontent.com/274968/82116123-9fd51d80-97aa-11ea-8cf9-c82f9c7c284d.gif)

whereas on mine I see this:

![mine](https://user-images.githubusercontent.com/274968/82116131-afecfd00-97aa-11ea-8bfa-bfd601b77a2b.gif)

Notice that mine doesn't have anything inside the `<use>` element, whereas the demo has the svg.

**Comment by klasjersevi** [comment]
Great, you have to include the svg sprite somewhere in the beginning of your page. You can style it as absolute positioned and 0x0 size, to make it invisible.

**Comment by klasjersevi** [comment]
See line 23 in the demo/index.html file to use a cachable js file that takes care of all that for the svg sprite.

**Comment by davidnash** [comment]
Fantastic, thanks! It's working now.

Just a note that this doesn't match the current instructions for Quill - eg with that you need only import the theme CSS, and you don't need the sprite.svg.

I'm having other issues, but I'll close this one. Thanks again.

**Comment by klasjersevi** [comment]
Yes, it's not supposed to be exactly like current quill. But I noticed that the instructions here really needs an update to explain everything.
